# Generated by Django 4.2.4 on 2023-08-19 09:54

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', profiles.models.CustomerUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], default=1, null=True, verbose_name='Gender')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('phone_number_1', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone Number 1')),
                ('phone_number_2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone Number 2')),
                ('city', models.CharField(blank=True, max_length=200, null=True, verbose_name='City')),
                ('country', models.CharField(blank=True, max_length=200, null=True, verbose_name='Country')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address')),
                ('interest', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ocean Lover'), (2, 'Environmental Activist'), (3, 'Conservationist'), (4, 'Educator'), (5, 'Researcher'), (6, 'Community Engager'), (7, 'Adventurer'), (8, 'Social Responsibility'), (9, 'Clean Future Advocate'), (10, 'Other')], default=3, null=True, verbose_name='Interest')),
                ('reason', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Plastic Cleanup Efforts'), (2, 'Gain Knowledge about Plastic Pollution'), (3, 'Spread Awareness about Ocean Plastic'), (4, 'Contribute to a Solution'), (5, 'Support Environmental Initiatives'), (6, 'Personal Growth and Learning'), (7, 'Community Involvement'), (8, 'Professional Networking'), (9, 'Inspire Others to Take Action'), (10, 'Other')], default=3, null=True, verbose_name='Reason')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='profiles.customeruser', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ('-create_at', '-update_at'),
            },
        ),
    ]
