# Generated by Django 4.2.4 on 2023-12-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interest',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ocean Lover'), (2, 'Environmental Activist'), (3, 'Conservationist'), (4, 'Educator'), (5, 'Researcher'), (6, 'Community Engager'), (7, 'Adventurer'), (8, 'Social Responsibility'), (9, 'Clean Future Advocate'), (10, 'Other')], default=10, null=True, verbose_name='Interest'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reason',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Plastic Cleanup Efforts'), (2, 'Gain Knowledge about Plastic Pollution'), (3, 'Spread Awareness about Ocean Plastic'), (4, 'Contribute to a Solution'), (5, 'Support Environmental Initiatives'), (6, 'Personal Growth and Learning'), (7, 'Community Involvement'), (8, 'Professional Networking'), (9, 'Inspire Others to Take Action'), (10, 'Other')], default=10, null=True, verbose_name='Reason'),
        ),
    ]
