# Generated by Django 4.2.4 on 2024-02-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_interest_alter_profile_reason'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.CheckConstraint(check=models.Q(('date_of_birth__year__lte', 2008), ('date_of_birth__isnull', True), _connector='OR'), name='age_must_be_gte_16', violation_error_message='Age must be at least 16 years'),
        ),
    ]
