# Generated by Django 5.1.3 on 2024-12-07 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=255, unique=True)),
                ('production_date', models.DateField(blank=True, null=True)),
                ('genres', models.CharField(default='', max_length=255)),
                ('runtime_minutes', models.IntegerField(default=0)),
                ('director_name', models.CharField(blank=True, max_length=255, null=True)),
                ('director_professions', models.CharField(blank=True, max_length=255, null=True)),
                ('director_birthYear', models.IntegerField(blank=True, null=True)),
                ('director_deathYear', models.IntegerField(blank=True, null=True)),
                ('movie_averageRating', models.FloatField(default=0.0)),
                ('movie_numerOfVotes', models.IntegerField(default=0)),
                ('approval_Index', models.FloatField(default=0.0)),
                ('production_budget', models.BigIntegerField(default=0)),
                ('domestic_gross', models.BigIntegerField(default=0)),
                ('worldwide_gross', models.BigIntegerField(default=0)),
            ],
        ),
    ]
