# Generated by Django 5.1.3 on 2024-12-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nancy', '0002_moviequery_delete_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviequery',
            name='movie_name',
        ),
        migrations.AddField(
            model_name='moviequery',
            name='query',
            field=models.CharField(blank=True, help_text="User's natural language query.", max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='moviequery',
            name='recommended_movies',
            field=models.TextField(help_text='Comma-separated list of recommended movies.'),
        ),
    ]
