# Generated by Django 5.1.3 on 2024-12-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nancy', '0003_remove_moviequery_movie_name_moviequery_query_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviequery',
            name='recommended_movies',
            field=models.TextField(blank=True, help_text='Comma-separated list of recommended movies.', null=True),
        ),
    ]
