# Generated by Django 5.1.3 on 2024-12-09 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nancy', '0005_genre_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
