# Generated by Django 5.1.3 on 2024-12-11 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_maininfo_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Movie Name')),
                ('genre', models.CharField(max_length=255, verbose_name='Genre')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Rating')),
                ('tmdb_id', models.IntegerField(unique=True, verbose_name='TMDB ID')),
                ('poster_path', models.URLField(blank=True, null=True, verbose_name='Poster URL')),
                ('overview', models.TextField(blank=True, null=True, verbose_name='Overview')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Release Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'ordering': ('-release_date',),
            },
        ),
        migrations.DeleteModel(
            name='AboutUs',
        ),
        migrations.DeleteModel(
            name='Award',
        ),
        migrations.DeleteModel(
            name='ContactUs',
        ),
        migrations.DeleteModel(
            name='CookiePolicy',
        ),
        migrations.DeleteModel(
            name='FAQs',
        ),
        migrations.DeleteModel(
            name='HeaderImage',
        ),
        migrations.DeleteModel(
            name='MainInfo',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
        migrations.DeleteModel(
            name='PrivacyPolicy',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
        migrations.DeleteModel(
            name='TermsOfService',
        ),
    ]
